# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
---
include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    cmake-args: >
    -DCONFIG_ZMK_SPLIT=y
    -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    -DCONFIG_BT_PERIPHERAL=y
    -DCONFIG_ZMK_USB=y
    -DCONFIG_ZMK_USB_LOGGING=y
  - board: seeeduino_xiao_ble
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_display
    snippet: studio-rpc-usb-uart zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset
